package CurrencyConvert;

import java.util.HashMap;
import java.util.Map;

public class CurrencyCountryMapper {
    private final Map<String, String> currencyCountryMap = new HashMap<>();

    public CurrencyCountryMapper() {
        addMapping("AED", "United Arab Emirates");
        addMapping("AFN", "Afghanistan");
        addMapping("ALL", "Albania");
        addMapping("AMD", "Armenia");
        addMapping("ANG", "Netherlands Antilles");
        addMapping("AOA", "Angola");
        addMapping("ARS", "Argentina");
        addMapping("AUD", "Australia");
        addMapping("AWG", "Aruba");
        addMapping("AZN", "Azerbaijan");
        addMapping("BAM", "Bosnia and Herzegovina");
        addMapping("BBD", "Barbados");
        addMapping("BDT", "Bangladesh");
        addMapping("BGN", "Bulgaria");
        addMapping("BHD", "Bahrain");
        addMapping("BIF", "Burundi");
        addMapping("BMD", "Bermuda");
        addMapping("BND", "Brunei");
        addMapping("BOB", "Bolivia");
        addMapping("BRL", "Brazil");
        addMapping("BSD", "The Bahamas");
        addMapping("BTN", "Bhutan");
        addMapping("BWP", "Botswana");
        addMapping("BYN", "Belarus");
        addMapping("BZD", "Belize");
        addMapping("CAD", "Canada");
        addMapping("CDF", "Democratic Republic of the Congo");
        addMapping("CHF", "Switzerland");
        addMapping("CLP", "Chile");
        addMapping("CNY", "China");
        addMapping("COP", "Colombia");
        addMapping("CRC", "Costa Rica");
        addMapping("CUP", "Cuba");
        addMapping("CVE", "Cape Verde");
        addMapping("CZK", "Czech Republic");
        addMapping("DJF", "Djibouti");
        addMapping("DKK", "Denmark");
        addMapping("DOP", "Dominican Republic");
        addMapping("DZD", "Algeria");
        addMapping("EGP", "Egypt");
        addMapping("ERN", "Eritrea");
        addMapping("ETB", "Ethiopia");
        addMapping("EUR", "European Union");
        addMapping("FJD", "Fiji");
        addMapping("FOK", "Faroese Krona");
        addMapping("FKP", "Falkland Islands");
        addMapping("GBP", "United Kingdom");
        addMapping("GEL", "Georgia");
        addMapping("GGP", "Guernsey");
        addMapping("GHS", "Ghana");
        addMapping("GIP", "Gibraltar");
        addMapping("GMD", "The Gambia");
        addMapping("GNF", "Guinea");
        addMapping("GTQ", "Guatemala");
        addMapping("GYD", "Guyana");
        addMapping("HKD", "Hong Kong");
        addMapping("HNL", "Honduras");
        addMapping("HRK", "Croatia");
        addMapping("HTG", "Haiti");
        addMapping("HUF", "Hungary");
        addMapping("IDR", "Indonesia");
        addMapping("ILS", "Israel");
        addMapping("IMP", "Isle of Man");
        addMapping("INR", "India");
        addMapping("IQD", "Iraq");
        addMapping("IRR", "Iran");
        addMapping("ISK", "Iceland");
        addMapping("JEP", "Jersey");
        addMapping("JMD", "Jamaica");
        addMapping("JOD", "Jordan");
        addMapping("JPY", "Japan");
        addMapping("KES", "Kenya");
        addMapping("KGS", "Kyrgyzstan");
        addMapping("KHR", "Cambodia");
        addMapping("KID", "Kiribati");
        addMapping("KMF", "Comoros");
        addMapping("KRW", "South Korea");
        addMapping("KWD", "Kuwait");
        addMapping("KYD", "Cayman Islands");
        addMapping("KZT", "Kazakhstan");
        addMapping("LAK", "Laos");
        addMapping("LBP", "Lebanon");
        addMapping("LKR", "Sri Lanka");
        addMapping("LRD", "Liberia");
        addMapping("LSL", "Lesotho");
        addMapping("LYD", "Libya");
        addMapping("MAD", "Morocco");
        addMapping("MDL", "Moldova");
        addMapping("MGA", "Madagascar");
        addMapping("MKD", "North Macedonia");
        addMapping("MMK", "Myanmar");
        addMapping("MNT", "Mongolia");
        addMapping("MOP", "Macau");
        addMapping("MRU", "Mauritania");
        addMapping("MUR", "Mauritius");
        addMapping("MVR", "Maldives");
        addMapping("MWK", "Malawi");
        addMapping("MXN", "Mexico");
        addMapping("MYR", "Malaysia");
        addMapping("MZN", "Mozambique");
        addMapping("NAD", "Namibia");
        addMapping("NGN", "Nigeria");
        addMapping("NIO", "Nicaragua");
        addMapping("NOK", "Norway");
        addMapping("NPR", "Nepal");
        addMapping("NZD", "New Zealand");
        addMapping("OMR", "Oman");
        addMapping("PAB", "Panama");
        addMapping("PEN", "Peru");
        addMapping("PGK", "Papua New Guinea");
        addMapping("PHP", "Philippines");
        addMapping("PKR", "Pakistan");
        addMapping("PLN", "Poland");
        addMapping("PYG", "Paraguay");
        addMapping("QAR", "Qatar");
        addMapping("RON", "Romania");
        addMapping("RSD", "Serbia");
        addMapping("RUB", "Russia");
        addMapping("RWF", "Rwanda");
        addMapping("SAR", "Saudi Arabia");
        addMapping("SBD", "Solomon Islands");
        addMapping("SCR", "Seychelles");
        addMapping("SDG", "Sudan");
        addMapping("SEK", "Sweden");
        addMapping("SGD", "Singapore");
        addMapping("SHP", "Saint Helena");
        addMapping("SLE", "Sierra Leone New");
        addMapping("SLL", "Sierra Leone Old");
        addMapping("SOS", "Somalia");
        addMapping("SRD", "Suriname");
        addMapping("SSP", "South Sudan");
        addMapping("STN", "Sao Tome and Principe");
        addMapping("SVC", "El Salvador");
        addMapping("SYP", "Syria");
        addMapping("SZL", "Eswatini");
        addMapping("THB", "Thailand");
        addMapping("TJS", "Tajikistan");
        addMapping("TMT", "Turkmenistan");
        addMapping("TND", "Tunisia");
        addMapping("TOP", "Tonga");
        addMapping("TRY", "Turkey");
        addMapping("TTD", "Trinidad and Tobago");
        addMapping("TVD", "Tuvalu");
        addMapping("TWD", "Taiwan");
        addMapping("TZS", "Tanzania");
        addMapping("UAH", "Ukraine");
        addMapping("UGX", "Uganda");
        addMapping("USD", "United States");
        addMapping("UYU", "Uruguay");
        addMapping("UZS", "Uzbekistan");
        addMapping("VES", "Venezuela");
        addMapping("VND", "Vietnam");
        addMapping("VUV", "Vanuatu");
        addMapping("WST", "Samoa");
        addMapping("XAF", "Central African CFA Franc");
        addMapping("XCD", "Eastern Caribbean");
        addMapping("XDR", "Special Drawing Rights");
        addMapping("XOF", "West African CFA Franc");
        addMapping("XPF", "CFP Franc");
        addMapping("YER", "Yemen");
        addMapping("ZAR", "South Africa");
        addMapping("ZMW", "Zambia");
        addMapping("ZWL", "Zimbabwe");
    }

    private void addMapping(String currencyCode, String countryName) {
        currencyCountryMap.put(currencyCode, countryName);
    }

    public String getCountryName(String currencyCode) {
        return currencyCountryMap.get(currencyCode);
    }


}
